spring:
  application:
    name: product

  data:
    mongodb:
      host: 211.62.140.88
      port: 27017
      auto-index-creation: true
      database: webflux
server:
  port: 8080

grpc:
  owner:
    host: localhost
    port: 6565